<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreConfig extends FormRequest
{	
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'server.name' => 'required|min:3|max:30',
        		'server.timezone' => 'required|timezone',
        		'server.speed' => 'required|min:1|max:9999999',
        		'server.troops_speed' => 'required|min:1|max:9999999',
        		'server.evasion_speed' => 'required|min:1|max:9999999',
        		'server.trader_capacity_multiplier' => 'required|min:1|max:9999999',
        		'server.cranny_capacity_multiplier' => 'required|min:1|max:9999999',
        		'server.trapper_capacity_multiplier' => 'required|min:1|max:9999999',
        		'server.storage_capacity_multiplier' => 'required|min:1|max:9999999',
        		'server.culture_points_multiplier' => 'required|min:1|max:9999999',
        		'server.world_size' => 'required|integer|in:25,50,100,150,200,250,300,350,400',
        		'server.registrations_open' => 'required|boolean',
        		'server.admin_statistics' => 'required|boolean',
        		'server.beginners_protection' => 'required|integer|min:0|max:720',
				'server.medals_interval' => 'required|integer|min:1|max:720',
        		'server.peace_type' => 'required|integer|between:0,4',
        		'server.start_date' => 'required|date',
        		'server.start_time' => 'required|date_format:H:i:s',
        		'server.quest' => 'required|boolean',
        		'server.activation_required' => 'required|boolean',
        		'server.demolish_level' => 'required|integer|min:1|max:20',
        		'server.village_expansion' => 'required|integer|between:0,1',
        		'natars.units_multiplier' => 'required|integer|min:1|max:9999999',
        		'natars.artefacts_release_date' => 'required|date',
        		'natars.artefacts_release_time' => 'required|date_format:H:i:s',
        		'natars.ww_release_date' => 'required|date',
        		'natars.ww_release_time' => 'required|date_format:H:i:s',
        		'natars.building_plans_release_date' => 'required|date',
        		'natars.building_plans_release_time' => 'required|date_format:H:i:s',
        		'natars.world_wonders_statistics' => 'required|boolean',
        		'natars.statistics' => 'required|boolean',
        		'oases.lumber_production_multiplier' => 'required|integer|min:1|max:9999999',
        		'oases.clay_production_multiplier' => 'required|integer|min:1|max:9999999',
        		'oases.iron_production_multiplier' => 'required|integer|min:1|max:9999999',
        		'oases.crop_production_multiplier' => 'required|integer|min:1|max:9999999',
        		'oases.troops_respawn_multiplier' => 'required|integer|min:1|max:9999999',
        		'oases.troops_multiplier' => 'required|integer|min:1|max:9999999',
        		'plus.account_duration' => 'required|integer|min:1|max:720',
        		'plus.production_duration' => 'required|integer|min:1|max:720',
        		'newsboxes.1' => 'required|boolean',
        		'newsboxes.2' => 'required|boolean',
        		'newsboxes.3' => 'required|boolean',
        		'logs.buildings' => 'required|boolean',
        		'logs.researches' => 'required|boolean',
        		'logs.upgrades' => 'required|boolean',
        		'logs.IP' => 'required|boolean',
        		'logs.gold' => 'required|boolean',
        		'logs.admin' => 'required|boolean',
        		'logs.market_movements' => 'required|boolean',
        		'logs.troops_training' => 'required|boolean',
        		'logs.login' => 'required|boolean',
        		'logs.logout' => 'required|boolean'
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array
     */
    public function attributes()
    {
    	return [
    			'server.name' => trans('installation/config.server_options.name'),
    			'server.timezone' => trans('installation/config.server_options.timezone'),
    			'server.speed' => trans('installation/config.server_options.speed'),
    			'server.troops_speed' => trans('installation/config.server_options.troops_speed'),
    			'server.evasion_speed' => trans('installation/config.server_options.evasion_speed'),
    			'server.trader_capacity_multiplier' => trans('installation/config.server_options.trader_capacity_multiplier'),
    			'server.cranny_capacity_multiplier' => trans('installation/config.server_options.cranny_capacity_multiplier'),
    			'server.trapper_capacity_multiplier' => trans('installation/config.server_options.trapper_capacity_multiplier'),
    			'server.storage_capacity_multiplier' => trans('installation/config.server_options.storage_capacity_multiplier'),
    			'server.culture_points_multiplier' => trans('installation/config.server_options.culture_points_multiplier'),
    			'server.world_size' => trans('installation/config.server_options.world_size'),
    			'server.registrations_open' => trans('installation/config.server_options.registrations_open'),
    			'server.admin_statistics' => trans('installation/config.server_options.show_admin_in_statistics'),
    			'server.beginners_protection' => trans('installation/config.server_options.beginners_protection_length'),
    			'server.medals_interval' => trans('installation/config.server_options.medals_interval'),
    			'server.peace_type' => trans('installation/config.server_options.peace_type.title'),
    			'server.start_date' => trans('installation/config.server_options.start_date'),
    			'server.start_time' => trans('installation/config.server_options.start_time'),
    			'server.quest' => trans('installation/config.server_options.quest'),
    			'server.activation_required' => trans('installation/config.server_options.activation_required'),
    			'server.demolish_level' => trans('installation/config.server_options.demolish_level'),
    			'server.village_expansion' => trans('installation/config.server_options.village_expansion'),
    			'natars.units_multiplier' => trans('installation/config.natars_options.units_multiplier'),
    			'natars.artefacts_release_date' => trans('installation/config.natars_options.artefacts_release_date'),
    			'natars.artefacts_release_time' => trans('installation/config.natars_options.artefacts_release_time'),
    			'natars.ww_release_date' => trans('installation/config.natars_options.world_wonders_release_date'),
    			'natars.ww_release_time' => trans('installation/config.natars_options.world_wonders_release_time'),
    			'natars.building_plans_release_date' => trans('installation/config.natars_options.building_plans_release_date'),
    			'natars.building_plans_release_time' => trans('installation/config.natars_options.building_plans_release_time'),
    			'natars.statistics' => trans('installation/config.natars_options.show_in_statistics'),
    			'natars.world_wonders_statistics' => trans('installation/config.natars_options.show_world_wonders_statistics'),
    			'oases.lumber_production_multiplier' => trans('installation/config.oases_options.lumber_production_multiplier'),
    			'oases.clay_production_multiplier' => trans('installation/config.oases_options.clay_production_multiplier'),
    			'oases.iron_production_multiplier' => trans('installation/config.oases_options.iron_production_multiplier'),
    			'oases.crop_production_multiplier' => trans('installation/config.oases_options.crop_production_multiplier'),
    			'oases.troops_respawn_multiplier' => trans('installation/config.oases_options.troops_respawn_multiplier'),
    			'oases.troops_multiplier' => trans('installation/config.oases_options.troops_multiplier'),
    			'plus.account_duration' => trans('installation/config.plus_features.production_length'),
    			'plus.production_duration' => trans('installation/config.plus_features.plus_account_length'),
    			'newsboxes.1' => trans('installation/config.newsboxes_options.newsbox') . 1,
    			'newsboxes.2' => trans('installation/config.newsboxes_options.newsbox') . 2,
    			'newsboxes.3' => trans('installation/config.newsboxes_options.newsbox') . 3,
    			'logs.buildings' => trans('installation/config.logs.buildings'),
    			'logs.researches' => trans('installation/config.logs.researches'),
    			'logs.upgrades' => trans('installation/config.logs.upgrades'),
    			'logs.IP' => trans('installation/config.logs.ip'),
    			'logs.gold' => trans('installation/config.logs.gold') ,
    			'logs.admin' => trans('installation/config.logs.admin'),
    			'logs.market_movements' => trans('installation/config.logs.market_movements'),
    			'logs.troops_training' => trans('installation/config.logs.troops_training'),
    			'logs.login' => trans('installation/config.logs.login'),
    			'logs.logout' => trans('installation/config.logs.logout')
    	];
    }
    
	/**
	 * Get the error messages for the defined validation rules.
	 *
	 * @return array
	 */
	public function messages(): array
	{
		return [
				'server.name.required' => trans('errors.required'),
				'server.name.min' => trans('errors.minimum'),
				'server.name.max' => trans('errors.maximum'),
				'server.timezone.required' => trans('errors.required'),
				'server.timezone.timezone' => trans('errors.timezone'),
				'server.speed.required' => trans('errors.required'),
				'server.speed.min' => trans('errors.minimum'),
				'server.speed.max' => trans('errors.maximum'),
				'server.troops_speed.required' => trans('errors.required'),
				'server.troops_speed.min' => trans('errors.minimum'),
				'server.troops_speed.max' => trans('errors.maximum'),
				'server.evasion_speed.required' => trans('errors.required'),
				'server.evasion_speed.min' => trans('errors.minimum'),
				'server.evasion_speed.max' => trans('errors.maximum'),
				'server.trader_capacity_multiplier.required' => trans('errors.required'),
				'server.trader_capacity_multiplier.min' => trans('errors.minimum'),
				'server.trader_capacity_multiplier.max' => trans('errors.maximum'),
				'server.trapper_capacity_multiplier.required' => trans('errors.required'),
				'server.trapper_capacity_multiplier.min' => trans('errors.minimum'),
				'server.trapper_capacity_multiplier.max' => trans('errors.maximum'),
				'server.cranny_capacity_multiplier.required' => trans('errors.required'),
				'server.cranny_capacity_multiplier.min' => trans('errors.minimum'),
				'server.cranny_capacity_multiplier.max' => trans('errors.maximum'),
				'server.trapper_capacity_multiplier.required' => trans('errors.required'),
				'server.trapper_capacity_multiplier.min' => trans('errors.minimum'),
				'server.trapper_capacity_multiplier.max' => trans('errors.maximum'),
				'server.storage_capacity_multiplier.required' => trans('errors.required'),
				'server.storage_capacity_multiplier.min' => trans('errors.minimum'),
				'server.storage_capacity_multiplier.max' => trans('errors.maximum'),
				'server.culture_points_multiplier.required' => trans('errors.required'),
				'server.culture_points_multiplier.min' => trans('errors.minimum'),
				'server.culture_points_multiplier.max' => trans('errors.maximum'),
				'server.world_size.required' => trans('errors.required'),
				'server.world_size.integer' => trans('errors.integer'),
				'server.world_size.in' => trans('errors.in'),
				'server.registrations_open.required' => trans('errors.required'),
				'server.registrations_open.boolean' => trans('errors.invalid'),
				'server.admin_statistics.required' => trans('errors.required'),
				'server.admin_statistics.boolean' => trans('errors.invalid'),
				'server.beginners_protection.required' => trans('errors.required'),
				'server.beginners_protection.integer' => trans('errors.integer'),
				'server.beginners_protection.min' => trans('errors.minimum'),
				'server.beginners_protection.max' => trans('errors.maximum'),
				'server.medals_interval.required' => trans('errors.required'),
				'server.medals_interval.integer' => trans('errors.integer'),
				'server.medals_interval.min' => trans('errors.minimum'),
				'server.medals_interval.max' => trans('errors.maximum'),
				'server.peace_type.required' => trans('errors.required'),
				'server.peace_type.integer' => trans('errors.integer'),
				'server.peace_type.between' => trans('errors.between'),
				'server.start_date.required' => trans('errors.required'),
				'server.start_date.date' => trans('errors.date'),
				'server.start_time.required' => trans('errors.required'),
				'server.start_time.date_format' => trans('errors.date_format'),
				'server.quest.required' => trans('errors.required'),
				'server.quest.boolean' => trans('errors.invalid'),
				'server.activation_required.required' => trans('errors.required'),
				'server.activation_required.boolean' => trans('errors.invalid'),
				'server.demolish_level.required' => trans('errors.required'),
				'server.demolish_level.integer' => trans('errors.integer'),
				'server.demolish_level.min' => trans('errors.minimum'),
				'server.demolish_level.max' => trans('errors.maximum'),
				'server.village_expansion.required' => trans('errors.required'),
				'server.village_expansion.integer' => trans('errors.integer'),
				'server.village_expansion.between' => trans('errors.between'),
				'natars.units_multiplier.required' => trans('errors.required'),
				'natars.units_multiplier.integer' => trans('errors.integer'),
				'natars.units_multiplier.min' => trans('errors.minimum'),
				'natars.units_multiplier.max' => trans('errors.maximum'),
				'natars.artefacts_release_date.required' => trans('errors.required'),
				'natars.artefacts_release_date.date' => trans('errors.date'),
				'natars.artefacts_release_time.required' => trans('errors.required'),
				'natars.artefacts_release_time.date_format' => trans('errors.date_format'),
				'natars.ww_release_date.required' => trans('errors.required'),
				'natars.ww_release_date.date' => trans('errors.date'),
				'natars.ww_release_time.required' => trans('errors.required'),
				'natars.ww_release_time.date_format' => trans('errors.date_format'),
				'natars.building_plans_release_date.required' => trans('errors.required'),
				'natars.building_plans_release_date.date' => trans('errors.date'),
				'natars.building_plans_release_time.required' => trans('errors.required'),
				'natars.building_plans_release_time.date_format' => trans('errors.date_format'),
				'natars.world_wonders_statistics.required' => trans('errors.required'),
				'natars.world_wonders_statistics.boolean' => trans('errors.invalid'),
				'natars.statistics.required' => trans('errors.required'),
				'natars.statistics.boolean' => trans('errors.invalid'),
				'oases.lumber_production_multiplier.required' => trans('errors.required'),
				'oases.lumber_production_multiplier.integer' => trans('errors.integer'),
				'oases.lumber_production_multiplier.min' => trans('errors.minimum'),
				'oases.lumber_production_multiplier.max' => trans('errors.maximum'),
				'oases.clay_production_multiplier.required' => trans('errors.required'),
				'oases.clay_production_multiplier.integer' => trans('errors.integer'),
				'oases.clay_production_multiplier.min' => trans('errors.minimum'),
				'oases.clay_production_multiplier.max' => trans('errors.maximum'),
				'oases.iron_production_multiplier.required' => trans('errors.required'),
				'oases.iron_production_multiplier.integer' => trans('errors.integer'),
				'oases.iron_production_multiplier.min' => trans('errors.minimum'),
				'oases.iron_production_multiplier.max' => trans('errors.maximum'),
				'oases.crop_production_multiplier.required' => trans('errors.required'),
				'oases.crop_production_multiplier.integer' => trans('errors.integer'),
				'oases.crop_production_multiplier.min' => trans('errors.minimum'),
				'oases.crop_production_multiplier.max' => trans('errors.maximum'),
				'oases.troops_respawn_multiplier.required' => trans('errors.required'),
				'oases.troops_respawn_multiplier.integer' => trans('errors.integer'),
				'oases.troops_respawn_multiplier.min' => trans('errors.minimum'),
				'oases.troops_respawn_multiplier.max' => trans('errors.maximum'),
				'oases.troops_multiplier.required' => trans('errors.required'),
				'oases.troops_multiplier.integer' => trans('errors.integer'),
				'oases.troops_multiplier.min' => trans('errors.minimum'),
				'oases.troops_multiplier.max' => trans('errors.maximum'),
				'plus.account_duration.required' => trans('errors.required'),
				'plus.account_duration.integer' => trans('errors.integer'),
				'plus.account_duration.min' => trans('errors.minimum'),
				'plus.account_duration.max' => trans('errors.maximum'),
				'plus.production_duration.required' => trans('errors.required'),
				'plus.production_duration.integer' => trans('errors.integer'),
				'plus.production_duration.min' => trans('errors.minimum'),
				'plus.production_duration.max' => trans('errors.maximum'),
				'newsboxes.1.required' => trans('errors.required'),
				'newsboxes.1.boolean' => trans('errors.invalid'),
				'newsboxes.2.required' => trans('errors.required'),
				'newsboxes.2.boolean' => trans('errors.invalid'),
				'newsboxes.3.required' => trans('errors.required'),
				'newsboxes.3.boolean' => trans('errors.invalid'),
				'logs.buildings.required' => trans('errors.required'),
				'logs.buildings.boolean' => trans('errors.invalid'),
				'logs.researches.required' => trans('errors.required'),
				'logs.researches.boolean' => trans('errors.invalid'),
				'logs.upgrades.required' => trans('errors.required'),
				'logs.upgrades.boolean' => trans('errors.invalid'),
				'logs.IP.required' => trans('errors.required'),
				'logs.IP.boolean' => trans('errors.invalid'),
				'logs.gold.required' => trans('errors.required'),
				'logs.gold.boolean' => trans('errors.invalid'),
				'logs.admin.required' => trans('errors.required'),
				'logs.admin.boolean' => trans('errors.invalid'),
				'logs.market_movements.required' => trans('errors.required'),
				'logs.market_movements.boolean' => trans('errors.invalid'),
				'logs.troops_training.required' => trans('errors.required'),
				'logs.troops_training.boolean' => trans('errors.invalid'),	
				'logs.login.required' => trans('errors.required'),
				'logs.login.boolean' => trans('errors.invalid'),
				'logs.logout.required' => trans('errors.required'),
				'logs.logout.boolean' => trans('errors.invalid')
		];
	}
}
