@component('manual.layout')
<p class="question">@lang('manual/village.questions.1')</p>
<p class="answer">@lang('manual/village.answers.1')</p>
<p class="question">@lang('manual/village.questions.2')</p>
<p class="answer">@lang('manual/village.answers.2')</p>
<p class="question">@lang('manual/village.questions.3')</p>
<p class="answer">@lang('manual/village.answers.3')</p>
<br/>
<table cellspacing="1" cellpadding="2" class="culture_points table_data">
   <thead>
      <tr>
         <td colspan="21">
            <h3>@lang('manual/village.culture_points')</h3>
         </td>
      </tr>
      <tr>
         <th rowspan="2">
            @lang('manual/village.buildings')
         </th>
         <th colspan="20">
            @lang('buildings.level')      
         </th>
      </tr>
      <tr>
         <th>
            1        
         </th>
         <th>
            2        
         </th>
         <th>
            3        
         </th>
         <th>
            4        
         </th>
         <th>
            5        
         </th>
         <th>
            6        
         </th>
         <th>
            7        
         </th>
         <th>
            8        
         </th>
         <th>
            9        
         </th>
         <th>
            10        
         </th>
         <th>
            11        
         </th>
         <th>
            12        
         </th>
         <th>
            13        
         </th>
         <th>
            14        
         </th>
         <th>
            15        
         </th>
         <th>
            16        
         </th>
         <th>
            17        
         </th>
         <th>
            18        
         </th>
         <th>
            19        
         </th>
         <th>
            20        
         </th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <th class="text">
            @lang('buildings.woodcutter')    
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.clay_pit')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.iron_mine')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.cropland')  
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.sawmill')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.brickyard')      
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.iron_foundry')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.grain_mill')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.bakery')       
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.warehouse')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.granary')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.blacksmith')        
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.armoury') 
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.tournament_square')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.main_building')        
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.rally_point')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.marketplace')        
         </th>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            19        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            39        
         </td>
         <td>
            46        
         </td>
         <td>
            55        
         </td>
         <td>
            67        
         </td>
         <td>
            80        
         </td>
         <td>
            96        
         </td>
         <td>
            115        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.embassy')        
         </th>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            8        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            14        
         </td>
         <td>
            17        
         </td>
         <td>
            21        
         </td>
         <td>
            25        
         </td>
         <td>
            30        
         </td>
         <td>
            36        
         </td>
         <td>
            43        
         </td>
         <td>
            51        
         </td>
         <td>
            62        
         </td>
         <td>
            74        
         </td>
         <td>
            89        
         </td>
         <td>
            106        
         </td>
         <td>
            128        
         </td>
         <td>
            153        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.barracks')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.stable')        
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.workshop')        
         </th>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            19        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            39        
         </td>
         <td>
            46        
         </td>
         <td>
            55        
         </td>
         <td>
            67        
         </td>
         <td>
            80        
         </td>
         <td>
            96        
         </td>
         <td>
            115        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.academy')        
         </th>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            8        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            14        
         </td>
         <td>
            17        
         </td>
         <td>
            21        
         </td>
         <td>
            25        
         </td>
         <td>
            30        
         </td>
         <td>
            36        
         </td>
         <td>
            43        
         </td>
         <td>
            51        
         </td>
         <td>
            62        
         </td>
         <td>
            74        
         </td>
         <td>
            89        
         </td>
         <td>
            106        
         </td>
         <td>
            128        
         </td>
         <td>
            153        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.cranny')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.town_hall')        
         </th>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            45        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
         <td>
            92        
         </td>
         <td>
            111        
         </td>
         <td>
            133        
         </td>
         <td>
            160        
         </td>
         <td>
            192        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.residence')        
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.palace')       
         </th>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            45        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
         <td>
            92        
         </td>
         <td>
            111        
         </td>
         <td>
            133        
         </td>
         <td>
            160        
         </td>
         <td>
            192        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.treasury')        
         </th>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            14        
         </td>
         <td>
            17        
         </td>
         <td>
            20        
         </td>
         <td>
            24        
         </td>
         <td>
            29        
         </td>
         <td>
            34        
         </td>
         <td>
            41        
         </td>
         <td>
            50        
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
         <td>
            &nbsp;
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.trade_office')        
         </th>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            19        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            39        
         </td>
         <td>
            46        
         </td>
         <td>
            55        
         </td>
         <td>
            67        
         </td>
         <td>
            80        
         </td>
         <td>
            96        
         </td>
         <td>
            115        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.great_barracks')        
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.great_stable')        
         </th>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            10        
         </td>
         <td>
            12        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            21        
         </td>
         <td>
            26        
         </td>
         <td>
            31        
         </td>
         <td>
            37        
         </td>
         <td>
            44        
         </td>
         <td>
            53        
         </td>
         <td>
            64        
         </td>
         <td>
            77        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.stonemason_lodge')      
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
      <tr>
         <th class="text">
            @lang('buildings.hero_mansion')     
         </th>
         <td>
            1        
         </td>
         <td>
            1        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            2        
         </td>
         <td>
            3        
         </td>
         <td>
            4        
         </td>
         <td>
            4        
         </td>
         <td>
            5        
         </td>
         <td>
            6        
         </td>
         <td>
            7        
         </td>
         <td>
            9        
         </td>
         <td>
            11        
         </td>
         <td>
            13        
         </td>
         <td>
            15        
         </td>
         <td>
            18        
         </td>
         <td>
            22        
         </td>
         <td>
            27        
         </td>
         <td>
            32        
         </td>
         <td>
            38        
         </td>
      </tr>
   </tbody>
</table>
<table cellspacing="1" cellpadding="2" class="table_data" style="table-layout:fixed;">
   <thead>
      <tr>
         <td colspan="10">
            <h3>@lang('manual/village.culture_points_needed')</h3>
         </td>
      </tr>
   </thead>
   <tbody>
      <tr>
         <th>
            1        
         </th>
         <th>
            2        
         </th>
         <th>
            3        
         </th>
         <th>
            4        
         </th>
         <th>
            5        
         </th>
         <th>
            6        
         </th>
         <th>
            7        
         </th>
         <th>
            8        
         </th>
         <th>
            9        
         </th>
         <th>
            10        
         </th>
      </tr>
      <tr align="center">
         <td>
            &nbsp; - &nbsp;
         </td>
         <td>
            2000        
         </td>
         <td>
            8000        
         </td>
         <td>
            20000        
         </td>
         <td>
            39000        
         </td>
         <td>
            65000        
         </td>
         <td>
            99000        
         </td>
         <td>
            141000        
         </td>
         <td>
            191000        
         </td>
         <td>
            251000        
         </td>
      </tr>
   </tbody>
</table>
<p>@lang('manual/village.culture_points_description')</p>

<div class="clear"></div>
@endcomponent